const CHARACTERS = [
  {id:'aldara',name:'Aldara',time:'HOY',image:'assets/aldara_medallon_v48.webp',role:'La investigadora',desc:'12 años. Vive en el presente. Curiosa, rápida y poco dispuesta a aceptar una leyenda porque “siempre se ha contado así”. Recorre Chinchilla con el móvil, observa el patrimonio y transforma cada parada en una investigación sobre el terreno.',quote:'«Si falta una página, todavía no conocemos la historia.»'},
  {id:'amina',name:'Amina',time:'SIGLO XIII',image:'assets/amina_master_v48.webp',role:'La hija del alcaide',desc:'Joven andalusí de Chinchilla. Inteligente, orgullosa y compasiva. Encuentra a Ferran herido después de una batalla y toma una decisión que pone en riesgo su posición y su familia.',quote:'«No te ayudo porque seas de los míos. Te ayudo porque estás herido.»'},
  {id:'ferran',name:'Ferran',time:'SIGLO XIII',image:'assets/ferran_master_v48.webp',role:'El caballero catalán',desc:'Joven caballero cristiano procedente de tierras catalanas. Orgulloso, irónico y leal. La herida le obliga a depender de alguien a quien le enseñaron a considerar enemiga.',quote:'«Me hablaron mucho de vuestra gente. Ninguno de ellos te conocía.»'},
  {id:'rajid',name:'Rajid',time:'SIGLO XIII',image:'assets/rajid_master_v49.webp',role:'El noble que decide por los demás',desc:'Noble andalusí y hombre de confianza del padre de Amina. Sereno, culto e inflexible. Cree que ocultar a Ferran pone en peligro a la familia y a la fortaleza; cuando encuentra la carta, decide que el deber está por encima de los sentimientos de Amina.',quote:'«Algunas decisiones no se toman por crueldad, sino por deber.»'}
];

const CHAPTERS = [
  {n:1,envPhoto:'assets/env/parada-1.jpg',title:'La leyenda rota',place:'Plaza de la Mancha',placeShort:'Plaza de la Mancha',kind:'DEDUCCIÓN',icon:'fa-solid fa-book-open-reader',difficulty:'INICIO',coord:[38.92085,-1.72510],image:'assets/aldara_medallon_v48.webp',minutes:4,
   question:'¿Ferran huyó sin despedirse o dejó un mensaje?',
   success:'Conectar las dos frases que convierten la leyenda en una contradicción.',
   story:'Aldara llega a Chinchilla con una frase subrayada en el cuaderno de su abuelo: “Ferran dejó una carta”. La leyenda, en cambio, insiste en que huyó sin despedirse. Si las dos cosas no pueden ser ciertas a la vez, alguien ha perdido —o escondido— una parte de la historia.',
   objective:'Leer tres fuentes y conectar las dos frases que convierten la leyenda en un caso abierto.',evidence:'FERRAN ESCRIBIÓ ANTES DE HUIR',memory:'Contradicción: “huyó sin despedirse” ↔ “dejó una carta”.',
   heritage:'Punto de arranque para presentar el casco histórico y cómo una plaza funciona como puerta de entrada al relato del pueblo.',
   lookfor:'Mirad alrededor y fijaos en cómo las plazas concentran pasos, memoria local y vistas hacia otros puntos del recorrido.',
   visitTip:'Perfecta para introducir la historia y explicar que la aventura mezcla ficción con patrimonio real.',realHistory:'La Plaza de la Mancha es el centro neurálgico de la villa y forma parte del Conjunto Histórico de Chinchilla, cuyo casco conserva trazado medieval y edificios de distintas épocas.',officialUrl:'https://www.turismocastillalamancha.es/es/destinos/encanto-rural/albacete/chinchilla-de-monte-aragon',
   hints:['No comparéis fechas todavía. Buscad dos frases sobre la despedida de Ferran.','Una fuente afirma que huyó sin despedirse; otra conserva algo que hizo antes de marcharse.','Conectad “huyó sin despedirse” con “dejó una carta”.']},
  {n:2,envPhoto:'assets/env/parada-2.jpg',title:'El caballero herido',place:'Entorno histórico / acceso bajo',placeShort:'Acceso bajo y entorno de muralla',kind:'ESCENA INVESTIGABLE',icon:'fa-solid fa-shoe-prints',difficulty:'INICIO',coord:[38.92110,-1.72560],image:'assets/ferran_master_v48.webp',minutes:5,
   question:'¿Cómo llegó Ferran hasta donde Amina lo encontró?',
   success:'Demostrar una cadena física de caída, separación, avance y llegada.',
   story:'La investigación retrocede hasta una escaramuza a las afueras. El caballo de Ferran regresa sin jinete. Él, herido, intenta alcanzar la ciudad a pie. Amina encuentra el final de ese recorrido antes que cualquier patrulla y comprende enseguida a quién tiene delante.',
   objective:'Inspeccionar el terreno, separar rastros útiles de objetos llamativos y reconstruir el recorrido de Ferran.',evidence:'EL CABALLO VOLVIÓ SIN ÉL',memory:'Cadena: estribo roto → caballo de regreso → sangre → tela en el paso.',
   heritage:'Un punto ideal para hablar de accesos, defensas y zonas de paso alrededor de la fortaleza.',
   lookfor:'Observad desniveles, entradas secundarias y rincones que podrían haber servido como refugio o escape.',
   visitTip:'Conviene detenerse un momento y leer el espacio como si fuera una escena: por dónde se entra, por dónde se huye y qué se controla desde arriba.',realHistory:'El casco antiguo conserva su trazado medieval sobre un enclave estratégico ocupado desde mucho antes. Durante la etapa musulmana Chinchilla alcanzó relevancia dentro del territorio de Tudmir.',officialUrl:'https://www.turismocastillalamancha.es/es/cultura-y-patrimonio/monumentos/albacete/conjunto-historico-de-chinchilla-de-montearagon',
   hints:['Buscad cuatro indicios que expliquen movimiento: caída, separación, avance a pie y acceso final.','La espada identifica un combate, pero no explica el recorrido. Seguid caballo, sangre y paso estrecho.','Estribo roto → huellas del caballo de regreso → rastro de sangre → tela enganchada.']},
  {n:3,envPhoto:'assets/env/parada-3.jpg',title:'El escondite',place:'Baños Árabes',placeShort:'Baños Árabes',kind:'PLANIFICACIÓN',icon:'fa-solid fa-droplet',difficulty:'MEDIO',coord:[38.92121,-1.72640],image:'assets/amina_cuida_ferran_v48.webp',minutes:5,
   question:'¿Cómo pudo Amina volver varias noches sin despertar sospechas?',
   success:'Construir y simular una visita que resuelva hora, ruta y necesidades de Ferran.',
   story:'Amina lo esconde y regresa para curarlo. La segunda visita ya no puede explicarse por impulso: tiene que estudiar rondas, oscuridad y qué puede transportar sin despertar preguntas. Entre una visita y la siguiente empiezan a hablar, a discutir y, sin admitirlo, a esperarse.',
   objective:'Leer las restricciones, construir un plan de visita y comprobarlo mediante una simulación paso a paso.',evidence:'AMINA VOLVIÓ MÁS DE UNA VEZ',memory:'Plan viable: último relevo + lateral de los baños + carga mínima.',
   heritage:'Los baños permiten introducir la vida cotidiana andalusí y explicar que no todo en una ciudad histórica gira en torno a murallas y batallas.',
   lookfor:'Fijaos en la idea de agua, cuidado, intimidad y tránsito discreto dentro de la ciudad.',
   visitTip:'Esta parada funciona muy bien si el acompañante explica cómo serían los hábitos cotidianos y el valor social del lugar.',realHistory:'Los Baños Árabes son un hammam de origen islámico, datado en el siglo XI, y el único conjunto de este tipo conservado en la provincia de Albacete. Tenían vestíbulo y salas fría, templada y caliente; hoy la visita es únicamente exterior porque son propiedad privada.',officialUrl:'https://www.turismocastillalamancha.es/es/cultura-y-patrimonio/monumentos/albacete/banos-arabes',
   hints:['No intentéis acertarlo todo de una vez: la simulación os dirá exactamente dónde falla el plan.','El último relevo reduce ojos en las calles y el lateral de los baños queda vacío tras el cierre.','23:00 + lateral de los baños + agua, vendas e higos secos. Máximo 3 unidades.']},
  {n:4,envPhoto:'assets/env/parada-4.jpg',title:'El camino de Amina',place:'Calles del casco histórico',placeShort:'Calles del casco histórico',kind:'MAPA + RUTA',icon:'fa-solid fa-route',difficulty:'MEDIO',coord:[38.92215,-1.72480],image:'assets/camino_amina_v48.webp',minutes:6,
   question:'¿Qué ruta permitía a Amina llegar sin cruzarse con las rondas?',
   success:'Alinear el croquis con la ciudad y simular una ruta sin entrar en sectores vigilados.',
   story:'Las visitas continúan. Amina memoriza esquinas, cambios de guardia y puntos de luz para llegar hasta Ferran sin ser vista. La ciudad se convierte en su lenguaje secreto.',
   objective:'Superponer un croquis antiguo sobre la ciudad actual y después simular una ruta que evite todos los sectores vigilados.',evidence:'EL CAMINO ERA SUYO',memory:'Ruta segura reconstruida: 1 → 3 → 5 → 7.',
   heritage:'Este capítulo recupera el valor turístico de perderse por el casco histórico y leer sus calles como un mapa vivo.',
   lookfor:'Balcón, esquina, arco, cuesta y cualquier elemento que ayude a imaginar recorridos escondidos.',
   visitTip:'Ideal para que el juego anime a levantar la vista y descubrir que una ruta puede contar una historia por sí sola.',realHistory:'Chinchilla conserva un casco histórico de calles empedradas, plazas, casas de piedra y un trazado medieval que mantiene huellas de su origen urbano árabe.',officialUrl:'https://www.turismocastillalamancha.es/es/cultura-y-patrimonio/monumentos/albacete/conjunto-historico-de-chinchilla-de-montearagon',
   hints:['Primero resolvemos orientación; después la ruta. No mezcleis las dos fases.','La sombra del croquis desaparece cuando torre, fuente y arco caen casi exactamente sobre sus equivalentes.','Alinead a 90° y sin desplazamiento. En la ruta, la rama segura evita los nodos 2, 4 y 6.']},
  {n:5,envPhoto:'assets/env/parada-5.jpg',title:'Palabras que nadie entiende',place:'Cuevas / zona de refugio',placeShort:'Cuevas y refugios',kind:'CÓDIGO POR CONTEXTO',icon:'fa-solid fa-feather-pointed',difficulty:'MEDIO',coord:[38.92348,-1.72418],image:'assets/lenguaje_secreto_v48.webp',minutes:6,
   question:'¿Qué significaban los signos que Amina y Ferran compartían?',
   success:'Confirmar cada símbolo en dos contextos y leer una nota completa.',
   story:'Para no escribir nombres, Amina y Ferran inventan pequeños signos. Primero sirven para sobrevivir. Después empiezan a decir cosas que ninguno se atreve a decir en voz alta.',
   objective:'Construir un pequeño diccionario usando dos contextos por símbolo y aplicar después ese lenguaje a una nota de Amina.',evidence:'VOLVERÉ',memory:'Símbolo clave: ↶ = VOLVER.',
   heritage:'Las cuevas y refugios refuerzan la idea de esconder, guardar y comunicar sin ser descubierto.',
   lookfor:'Pensad en espacios pequeños, discretos y resguardados donde un mensaje secreto tendría sentido.',
   visitTip:'Una parada estupenda para mezclar imaginación, detalle arquitectónico y juego simbólico.',realHistory:'A los pies de las murallas se conservan casas-cueva excavadas en el cerro, reconocibles por sus chimeneas blancas. Son uno de los elementos más singulares de la arquitectura popular de Chinchilla.',officialUrl:'https://www.turismocastillalamancha.es/es/destinos/encanto-rural/albacete/chinchilla-de-monte-aragon',
   hints:['No aceptéis una traducción porque encaje una vez: debe funcionar en las dos apariciones del símbolo.','Empezad por los signos apoyados por objetos o momentos muy concretos, como la jarra o la noche.','El mensaje final se lee como: ESPERA AQUÍ · VOLVERÉ DE NOCHE.']},
  {n:6,envPhoto:'assets/env/parada-6.jpg',title:'Alguien los vio',place:'Zona alta / mirador',placeShort:'Mirador y zona alta',kind:'LÍNEA DE VISIÓN',icon:'fa-solid fa-eye',difficulty:'MEDIO–ALTO',coord:[38.92190,-1.72720],image:'assets/rajid_observa_v48.webp',minutes:5,
   question:'¿Desde dónde fueron observados y quién estaba allí?',
   success:'Orientar la luz, demostrar una línea de visión doble y cruzarla con el registro.',
   story:'Una de las noches alguien observa a Amina entrar en el refugio. No sabemos aún quién fue, pero una lámpara, una pared y la dirección de una sombra permiten reconstruir desde dónde miraba.',
   objective:'Reconstruir primero la posición de la luz, después demostrar una línea de visión doble y por último cruzarla con el registro de presencia.',evidence:'RAJID LOS DESCUBRIÓ',memory:'Galería norte · observador confirmado: Rajid.',
   heritage:'Los miradores ayudan a explicar control visual, vigilancia y dominio del territorio.',
   lookfor:'Buscad puntos con amplitud visual y pensad qué zonas del pueblo quedan expuestas desde allí.',
   visitTip:'Sirve para enseñar a leer la topografía del lugar y cómo la altura condiciona la historia.',realHistory:'La posición elevada de Chinchilla explica su valor estratégico: desde el cerro se domina la llanura manchega y las rutas del entorno. Esa relación entre altura, vigilancia y territorio marcó su historia defensiva.',officialUrl:'https://www.turismocastillalamancha.es/es/cultura-y-patrimonio/castillos/albacete/castillo-de-chinchilla-de-montearag-n',
   hints:['La sombra cae alejándose de la lámpara. Usadla para orientar la escena antes de probar observadores.','Cuando la luz esté bien situada, buscad un punto desde el que el muro no corte ninguna de las dos líneas.','La lámpara queda al noroeste; la única visión completa sale de la galería norte. El registro coloca allí a Rajid.']},
  {n:7,envPhoto:'assets/env/parada-7.jpg',title:'La huida',place:'Exterior de la fortaleza',placeShort:'Exterior de la fortaleza',kind:'PATRÓN DE GUARDIAS',icon:'fa-solid fa-chess-knight',difficulty:'ALTO',coord:[38.91895,-1.72820],image:'assets/amina_ferran_despedida_v48.webp',minutes:6,
   question:'¿Cómo escapó Ferran y dónde dejó la carta para Amina?',
   success:'Encontrar una secuencia segura de movimiento y usar su código compartido para ocultar el mensaje.',
   story:'Rajid ya sabe la verdad. Ferran comprende que si lo capturan también pondrá a Amina en peligro. Tiene que marcharse esa misma noche. Antes de hacerlo, deja una carta en el lugar acordado.',
   objective:'Leer el ciclo de patrullas, mover a Ferran nodo a nodo y dejar la carta en un escondite que solo Amina pueda reconocer.',evidence:'FERRAN DEJÓ LA CARTA',memory:'Último tramo de huida: PASO NORTE. La carta quedó bajo la marca ⌂.',
   heritage:'La fortaleza entra aquí como espacio estratégico: accesos, presión, patrullas y sensación de encierro.',
   lookfor:'Localizad puertas, muros, puntos ciegos y zonas donde una huida sería más o menos viable.',
   visitTip:'Es una parada muy visual para transformar la arquitectura en un tablero de tensión.',realHistory:'El castillo actual es principalmente una fortificación del siglo XV levantada sobre una fortaleza de origen islámico. Su espectacular foso está tallado en la roca. Importante: su aspecto actual es posterior a la época en la que situamos la ficción de Amina y Ferran.',officialUrl:'https://www.turismocastillalamancha.es/es/cultura-y-patrimonio/castillos/albacete/castillo-de-chinchilla-de-montearag-n',
   hints:['Cada acción hace avanzar una ronda. Si salís de inmediato, el arco queda cubierto. A veces la mejor primera jugada es esperar.','Después de esperar una ronda, buscad una cadena de nodos que vaya quedando libre justo cuando Ferran llega.','Esperad una ronda y avanzad por ARCO → PATIO → MURO → PASO NORTE → SALIDA. Luego usad la marca ⌂ para esconder la carta.']},
  {n:8,envPhoto:'assets/env/parada-8.jpg',title:'La mentira de Rajid',place:'Castillo / exterior',placeShort:'Castillo y archivo',kind:'DOCUMENTOS SUPERPUESTOS',icon:'fa-solid fa-scroll',difficulty:'ALTO',coord:[38.91855,-1.72885],image:'assets/rajid_esconde_carta_v48.webp',minutes:7,
   question:'¿Qué ocurrió con la carta después de que Ferran la dejara?',
   success:'Alinear documentos, revelar la nota oculta y demostrar que la firma pertenece a Rajid.',
   story:'Amina espera una explicación que nunca llega. Rajid encuentra la carta antes que ella y la oculta. Amina cree que Ferran la utilizó y la abandonó. La leyenda dice que enfermó y murió de pena. Ferran, lejos de allí, sigue esperando una respuesta.',
   objective:'Manipular físicamente dos documentos, revelar la anotación oculta, identificar su firma y reconstruir qué ocurrió después.',evidence:'RAJID OCULTÓ EL MENSAJE',memory:'Prueba documental: “NO ENTREGAR · R.”',
   heritage:'Introduce el valor de los documentos, archivos y rastros escritos como parte de la memoria histórica.',
   lookfor:'Imaginad dónde se guardaría un mensaje, quién tendría acceso y qué significa borrar una prueba.',
   visitTip:'Muy útil para conectar patrimonio material, escritura y construcción de la memoria colectiva.',realHistory:'La fortaleza visible hoy pertenece sobre todo al siglo XV, aunque el enclave defensivo tiene raíces islámicas. El castillo fue además utilizado como prisión y domina visualmente todo el conjunto urbano.',officialUrl:'https://www.turismocastillalamancha.es/es/cultura-y-patrimonio/castillos/albacete/castillo-de-chinchilla-de-montearag-n',
   hints:['Arrastrad el documento superior hasta que sus tres marcas ⊕ coincidan con las de abajo. El medidor os indica si os acercáis.','Cuando el papel encaje, ajustad la transparencia y examinadlo a contraluz. Después comparad la R con el registro de la galería norte.','La anotación revela “NO ENTREGAR · R.” La cronología correcta es: Ferran escribe → Rajid intercepta → Amina busca → no recibe respuesta.']},
  {n:9,envPhoto:'assets/env/parada-9.jpg',title:'La carta que nunca llegó',place:'Castillo · desenlace',placeShort:'Castillo y desenlace',kind:'CASO FINAL',icon:'fa-solid fa-envelope-open',difficulty:'FINAL',coord:[38.91882,-1.72858],image:'assets/carta_final_v48.webp',minutes:7,
   question:'¿Qué cadena de decisiones convirtió una despedida en una tragedia?',
   success:'Reconstruir el caso, abrir el legajo con tres pruebas anteriores y recomponer la carta.',
   story:'Aldara ya conoce casi toda la tragedia. Amina murió creyendo que Ferran la había abandonado. Cuando Ferran se enteró, regresó consumido por la rabia y murió durante un asalto a la fortaleza. Solo falta una prueba capaz de demostrar qué ocurrió realmente entre ambos.',
   objective:'Reconstruir la cadena completa del caso, abrir el legajo con tres hallazgos anteriores y recomponer la carta de Ferran.',evidence:'LA VERDAD',memory:'Clave final: PASO NORTE · ↶ = VOLVER · R = RAJID.',
   heritage:'El cierre devuelve sentido al recorrido: el patrimonio deja de ser decorado y se convierte en escenario de una verdad recuperada.',
   lookfor:'Pensad en el castillo como el lugar donde memoria, poder y destino terminan cruzándose.',
   visitTip:'La experiencia culmina cuando el visitante comprende que ha conocido lugares reales mientras resolvía una ficción emotiva.',realHistory:'Chinchilla está protegida como Conjunto Histórico. Su patrimonio reúne castillo y murallas, baños árabes, cuevas, arquitectura civil y religiosa y un trazado urbano que permite leer distintas etapas de su historia.',officialUrl:'https://www.turismocastillalamancha.es/es/cultura-y-patrimonio/monumentos/albacete/conjunto-historico-de-chinchilla-de-montearagon',
   hints:['El muro final no se ordena por capítulos, sino por causa: qué tuvo que pasar para que el siguiente hecho fuera posible.','La caja usa tres recuerdos concretos: el último paso seguro de la huida, el símbolo de VOLVER y la firma del interceptor.','Cadena: herida → promesa → Rajid los ve → Ferran deja la carta → Rajid la intercepta → Amina espera. Caja: NORTE · ↶ · R.']}
];

/* V57 · rediseño de mecánicas de campo. La ubicación deja de ser un extra y pasa a formar parte del bucle de juego. */
const FIELD_CONFIG = {
  1:{title:'La grieta en la leyenda',kind:'RASTREO DE CAMPO',difficulty:'INICIO',radius:85,minutes:5,
    question:'Activa el punto de la Plaza, registra tres rastros y abre la grieta de la leyenda.',
    success:'Revelar físicamente los fragmentos y encajar la carta en el único hueco posible.',
    fieldPrompt:'Busca un punto tranquilo de la Plaza de la Mancha. El GPS debe situarte dentro de la zona antes de abrir el caso.',
    fieldAction:'Al llegar, la plaza se convierte en el tablero de investigación.'},
  2:{title:'Rastro de Ferran',kind:'CÁMARA + RASTREO',difficulty:'INICIO',radius:95,minutes:6,
    question:'Documenta un paso real del entorno y reconstruye el avance de Ferran sobre el terreno.',
    success:'Tomar una prueba fotográfica local y completar el rastro sin saltar ningún indicio.',
    fieldPrompt:'Sitúate en el acceso bajo o junto a un punto de paso reconocible. La cámara será parte de la prueba.',
    fieldAction:'Fotografía un acceso, desnivel o estrechamiento; la imagen no se sube a ningún servidor.'},
  3:{title:'La visita imposible',kind:'SIGILO TÁCTIL',difficulty:'MEDIO',radius:80,minutes:6,
    question:'Entrega tres suministros atravesando una ronda móvil sin ser detectado.',
    success:'Completar tres cruces de sigilo y entregar agua, vendas y alimento.',
    fieldPrompt:'Acércate a los Baños Árabes y observa el espacio exterior antes de empezar la simulación.',
    fieldAction:'El lugar activa una pequeña misión de sigilo inspirada en las visitas nocturnas de Amina.'},
  4:{title:'Calles de sombra',kind:'MOVIMIENTO + MAPA',difficulty:'MEDIO',radius:110,minutes:7,
    question:'Camina por el casco para calibrar el mapa y después traza una ruta sin entrar en las zonas vigiladas.',
    success:'Registrar al menos 18 m de movimiento real y superar el laberinto de vigilancia.',
    fieldPrompt:'Entra en las calles del casco histórico. No hace falta seguir una dirección concreta: muévete solo por zonas seguras y peatonales.',
    fieldAction:'Tu desplazamiento real calibra el mapa de Amina antes del puzle.'},
  5:{title:'El código escondido',kind:'CÁMARA + TRAZO',difficulty:'MEDIO',radius:110,minutes:6,
    question:'Captura una textura del entorno y recupera sobre ella los símbolos del código secreto.',
    success:'Registrar la escena y trazar el símbolo de regreso para revelar el mensaje.',
    fieldPrompt:'Busca una textura, piedra, cueva, chimenea o rincón que represente esta zona de refugio.',
    fieldAction:'La foto se convierte en el soporte del código; el reto ocurre encima de vuestra propia imagen.'},
  6:{title:'Ojos sobre la ciudad',kind:'BRÚJULA + VISIÓN',difficulty:'MEDIO–ALTO',radius:120,minutes:5,
    question:'Orienta el móvil hacia la fortaleza y mantén la línea de visión hasta fijar el punto de observación.',
    success:'Bloquear la dirección del castillo durante dos segundos usando la brújula del dispositivo.',
    fieldPrompt:'Busca un punto abierto de la zona alta o mirador desde el que puedas orientarte hacia la fortaleza.',
    fieldAction:'La brújula del teléfono sustituye a una pregunta: tendrás que encontrar la dirección real.'},
  7:{title:'La ventana de fuga',kind:'REFLEJOS + PATRULLAS',difficulty:'ALTO',radius:120,minutes:6,
    question:'Cruza tres sectores en el único instante en que las patrullas dejan una ventana abierta.',
    success:'Encadenar tres cruces sin entrar en el cono de vigilancia.',
    fieldPrompt:'Llega al exterior de la fortaleza y busca un lugar seguro donde detenerte; no juegues caminando.',
    fieldAction:'El entorno desbloquea una secuencia de patrullas que exige observación y reflejos.'},
  8:{title:'El documento fantasma',kind:'CÁMARA + SUPERPOSICIÓN',difficulty:'ALTO',radius:105,minutes:7,
    question:'Usa una imagen real del castillo como mesa de luz y alinea sobre ella el documento interceptado.',
    success:'Capturar el fondo, alinear tres marcas y hacer aparecer el sello de Rajid.',
    fieldPrompt:'Sitúate en el exterior del castillo y encuadra piedra, muro o acceso sin fotografiar a otras personas.',
    fieldAction:'La escena real se convierte en el fondo de una mesa de documentos aumentada.'},
  9:{title:'La carta que nunca llegó',kind:'FINAL DE CAMPO',difficulty:'FINAL',radius:120,minutes:8,
    question:'Activa las tres cerraduras del caso y reconstruye la carta final.',
    success:'Validar presencia, orientación y evidencias acumuladas; después montar la carta completa.',
    fieldPrompt:'Permanece en la zona del castillo. El final solo se abre tras una última comprobación de campo.',
    fieldAction:'La ubicación real y lo descubierto durante la ruta abren el archivo final.'}
};
CHAPTERS.forEach(ch=>Object.assign(ch,FIELD_CONFIG[ch.n]||{}));
const FIELD_HINTS={
1:['Mueve el escáner lentamente: los rastros aparecen en tres zonas distintas.','Cuando tengas 3/3, mira el hueco temporal, no el contenido de las frases.','La carta debe ocurrir después de recuperarse y antes de huir.'],
2:['La foto solo activa el escenario; después piensa en movimiento físico.','Primero hay una caída/separación, después señales de avance a pie.','Estribo → caballo que regresa → sangre → tela en el paso.'],
3:['No pulses nada más ver un hueco: observa un ciclo completo.','El cruce es seguro cuando el guardia está claramente en uno de los extremos.','Haz tres cruces limpios; cada ronda cambia ligeramente de ritmo.'],
4:['Detente para mirar la pantalla: el juego suma distancia GPS entre posiciones consecutivas.','En el mapa, una zona roja puede conectar, pero no es una ruta válida.','La rama segura evita 2, 4 y 6.'],
5:['Empieza el gesto por el punto luminoso superior derecho.','No levantes el dedo y pasa cerca de cada punto en orden.','El trazo forma ↶, el signo de VOLVER.'],
6:['Activa la brújula con el botón; en iPhone el permiso necesita un toque del usuario.','Gira despacio y mantente parado; la flecha muestra la diferencia con la fortaleza.','Cuando baje de unos 14°, mantén la posición durante dos segundos.'],
7:['Mira los dos guardias, no solo uno.','La franja central debe quedar vacía a la vez para ambos.','Supera tres sectores; el ritmo cambia después de cada cruce.'],
8:['Empieza ajustando horizontal y vertical antes de tocar la rotación.','Las tres cruces del papel deben caer sobre las tres marcas luminosas.','La posición objetivo está cerca del centro y la rotación es ligeramente positiva.'],
9:['La presencia y las ocho evidencias deberían estar ya validadas al llegar.','La tercera cerradura pide mirar de nuevo hacia el punto donde empezó la aventura.','Después ordena la carta como texto humano: motivo, promesa, advertencia y firma.']};
CHAPTERS.forEach(ch=>{if(FIELD_HINTS[ch.n])ch.hints=FIELD_HINTS[ch.n]});
